# This is a basic workflow to help you get started with Actions

name: Generate build number

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Allows reuse of this workflow from another workflow
  workflow_call:
    outputs:
      build_number:
        description: "The generated build number"
        value: ${{ jobs.main.outputs.build_number }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  main:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.generate_id.outputs.build_number }}

    steps:
      - id: generate_id
        name: Generate an ID
        run: |
          echo "build: $GITHUB_RUN_NUMBER"
          echo "build_number=$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT
