# This is a basic workflow to help you get started with Actions

name: Generate build number

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Allows reuse of this workflow from another workflow
  workflow_call:
    outputs:
      build_number:
        description: "The generated build number"
        value: ${{ jobs.generate.outputs.output1 }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.build_number }}

    steps:
      - name: Generate the build number and store it in the env
        run: |
          echo "build_number=$GITHUB_RUN_ATTEMPT" >> $GITHUB_OUTPUT
