# This is a basic workflow to help you get started with Actions

name: Increment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "plop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Allows reuse of this workflow from another workflow
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate the build number and store it in the env
        run: |
          echo $GITHUB_RUN_ATTEMPT
          echo "build_number=$GITHUB_RUN_ATTEMPT" >> $GITHUB_ENV
